### ISSUE TITLE
Improve main.py and remove hardcoded values from display.py

### ISSUE THREAD

**Issue by LucasPilla** [LucasPilla/Sorting-Algorithms-Visualizer#176] opened 2023-12-02 03:35 UTC
- Make main.py more readable by adding some comments
- Remove hardcoded values from display.py and move all global definitions to another file (a new one or main.py)

**Comment by LucasPilla** [comment] 2023-12-02 17:09
Sure @PedramHaeri, when you're done I can assign the other one to you if it is still free.

**Comment by hlai1** [comment] 2023-12-08 16:32
Hi @LucasPilla! I know @PedramHaeri is assigned to this issue but I've just submitted a PR (#183) to solve the issues listed in this. Please take a look if you have some time!

**Comment by sebas-inf** [comment] 2024-01-21 03:20
As the issue seems to still be open could I be assigned the issue?

**Comment by Manishmrgn** [comment] 2024-05-14 16:37
Hi @LucasPilla I would like to contribute to this issue. Could I be assigned to this issue?

**Comment by Devn913** [comment] 2024-07-12 08:52
The issue is still open. Is anyone trying, or Can I try?

**Comment by Dxuian** [comment] 2024-08-23 02:53
is this still open ?

**Closed** 2024-09-16 04:14 UTC
Labels: enhancement, good first issue, help-wanted
